[package]
name = "spriter"
version = "0.1.0"
authors = ["zvoleg <oleg.zaitsevv@gmail.com>"]
edition = "2018"

autoexamples = true

[dev-dependencies]
rand = "*"

[dependencies]
glutin = "0.25"
gl = "0.14"
lazy_static = "1.4"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
