[package]
name = "spriter"
version = "0.1.0"
authors = ["RustySkill <rustySkilll@gmail.com>"]
edition = "2018"

autoexamples = true

[dev-dependencies]
rand = "*"

[dependencies]
glutin = "0.25"
gl = "0.14"
lazy_static = "1.4"